---
repos:
  - repo: https://github.com/Lucas-C/pre-commit-hooks.git
    rev: v1.4.2
    hooks:
      - id: remove-tabs

  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
        exclude: tsconfig.json|.vscode/launch.json
      - id: check-symlinks
      - id: detect-private-key

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.29.0
    hooks:
      - id: yamllint
        files: \.(yaml|yml)$
        types: [file, yaml]
        entry: yamllint --strict -c yamllint-config.yaml
