apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aicoe-meteor
resources:
- deployment.yaml
- rolebinding.yaml
- role.yaml
- route.yaml
- service.yaml
- serviceaccount.yaml
- servicemonitor.yaml
images:
- name: meteor-shower
  newName: quay.io/aicoe/meteor-shower
  newTag: v0.0.1
