# permissions for end users to edit meteors.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: meteor-shower
rules:
  - apiGroups:
      - meteor.zone
    resources:
      - meteors
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - meteor.zone
    resources:
      - meteors/status
    verbs:
      - get
