apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: meteor-shower
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: meteor-shower
subjects:
    - kind: ServiceAccount
      name: meteor-shower
