apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: meteor-shower-monitor
spec:
  endpoints:
    - path: /metrics
      port: http
      scheme: http
  selector:
    matchLabels:
      app: meteor-shower
